### ISSUE TITLE
No Error Message with Login

### ISSUE THREAD

**Issue by bretrbs** [cs340tabyu/cs340Winter2018#113]
If the server is unavailable, there is no message informing the client that the server is down and that login/register is not possible.

**Comment by bretrbs** [comment]
I did receive an error after clicking the button ~50 times. Possibly you have a timeout that gives it a really long time to try to connect before showing the connection error.

**Comment by jerrod-storm** [comment]
Hmm. That would be a problem. I can't seem to reproduce this one either, though. If the server is down, I get a message almost instantaneously upon trying to login/register. I'll keep this one in mind, though.

**Comment by thejacobseely** [comment]
I was able to reproduce the error. It seems to only be with certain IP's...I'm not sure why.

I added a timeout, so now an error is shown within a reasonable amount of time.
