### ISSUE TITLE
History: duplicate entries and missing entries on game starts

### ISSUE THREAD

**Issue by nschulzke** [cs340tabyu/cs340Winter2018#140]
<img width="335" alt="screen shot 2018-03-28 at 3 22 13 pm" src="https://user-images.githubusercontent.com/2680092/38057414-a0127f92-329c-11e8-958a-2c0bd657aa63.png">

See screenshot. Nathan started the game, which is logged twice. Nathan got 4 train cards twice, no one else got any, according to the history.

**Comment by edenknudson** [comment]
We fixed this issue
