### ISSUE TITLE
Can claim gray routes using a mix of colors

### ISSUE THREAD

**Issue by nschulzke** [cs340tabyu/cs340Winter2018#145]
![image](https://user-images.githubusercontent.com/2680092/38057607-3944042e-329d-11e8-8e18-b45f76901f17.png)

I can claim a route using a mix of several colors. This isn't valid according to the rules, and, in fact, I got a toast saying "Wrong cards chosen", but it let me claim it anyway. It's supposed to require a set of the same color.

**Comment by edenknudson** [comment]
Really easy fix. We just forgot to return when the colors are not the same.
