### ISSUE TITLE
Backgrounds for text

### ISSUE THREAD

**Issue by nschulzke** [cs340tabyu/cs340Winter2018#152]
The image backgrounds are cool, but maybe add a transparency? In history, the white text is sometimes invisible, and we can't see the fourth player in the Player Status screen at all.

<img width="605" alt="screen shot 2018-03-28 at 3 36 55 pm" src="https://user-images.githubusercontent.com/2680092/38057883-1cbad818-329e-11e8-8a67-178d6ca27166.png">

**Comment by edenknudson** [comment]
We put a transparent white background on each item.
