### ISSUE TITLE
Can open the claim route window twice

### ISSUE THREAD

**Issue by nschulzke** [cs340tabyu/cs340Winter2018#172]
This is a weird one. Steps we took:

1. Player 1 clicked on Claim Route. It didn't respond, so he clicked again.
2. Player 1 claimed a route.
3. The Claim Route screen closed, but there was another one underneath.
4. Player 1 claimed a second route.
5. Player 2 and Player 3 both think it's their turn, both can move.

For all subsequent turns, two players had their turn at the same time. Player 3 took a turn and then Player 2 and 4 both thought it was their turn.

This is complicated to explain in text, feel free to ask one of us for a better explanation.

Simple solution: disable the button instantly when it's clicked.

**Comment by edenknudson** [comment]
We disabled the button as soon as it is clicked.
