### ISSUE TITLE
Username with spaces crashes registration

### ISSUE THREAD

**Issue by jonah-henderson** [cs340tabyu/cs340Winter2018#208]
To reproduce
1. Open the app
2. Enter a username containing spaces
3. Enter any valid password
4. Tap "Register"

**Comment by jerrod-storm** [comment]
I tried this with several names containing spaces. Couldn't seem to reproduce the crash.

**Comment by jacobgb24** [comment]
Also tested with the username reported by our crash logs - "really complicated user3wT$/r4#Q$***" and bug was not reproduced. Crash report was in line with crashes that occur when the server is stopped while the app is in use. This is a known crash that is related to phase 4.
