### ISSUE TITLE
Can't claim a double route

### ISSUE THREAD

**Issue by jonah-henderson** [cs340tabyu/cs340Winter2018#237]
tried with SLC to Denver

Reproduce:
1. Player 1 claims the yellow SLC -> Denver route
2. Player 1 on subsequent turns can't claim the red SLC -> Denver route (as expected)
3. Player 2 sees no highlight for the red SLC -> Denver on a claim action, even with sufficient cards (3 red, 1 locomotive), can't tap

**Comment by wconnorr** [comment]
This is expected behavior: according to the rules, only one side of a double route can be claimed in 2-3 player games.
