### ISSUE TITLE
Route points are wrong

### ISSUE THREAD

**Issue by kodycd09** [cs340tabyu/cs340Winter2018#243]
Currently each route is assigned points where 1 train = 1 point, 6 trains = 6 points.

Should follow here:
https://www.google.com/search?q=ticket+to+ride+points&rlz=1C1GCEA_enUS781US781&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjsu7H3m5DaAhVT9WMKHan1CcIQ_AUICygC&biw=1707&bih=816&dpr=1.13#imgrc=qlMS9c_cL4pZ8M:

Don't know where all it happens, but for sure here:
Aragog - Durmstrang - Dumbledore - Thestrals is 13 point route and 13 trains to get there, I had 26 points.  Should have more.  (had a 9 point unreached destination) and the longest route, neither of which impacted the displayed score

**Comment by Rob1kelly15** [comment]
fixed
