### ISSUE TITLE
End points calculated incorrectly

### ISSUE THREAD

**Issue by kodycd09** [cs340tabyu/cs340Winter2018#246]
Originally I was given points for completing Aragog - Dumbledore (top left, bottom left) but in the end-game it says I have 0 points, 0 completed.

Should've been 13 completed points, 17 not completed, 20/20 in my route (giving me longest route).
Instead I was given:
Kody: SECOND PLACE
Score: 7
Completed Destination Card Points: 0
Incompleted Destination Card Points: -30
Spells Left: 0

Other player:
clay: WINNER
Score: 16
Completed Destination Card Points: 11
Incompleted Destination Card Points: -25
Spells Left: 2

I don't know his cards, but he had a fork in his route which guarantees I had the longest route.

**Comment by Rob1kelly15** [comment]
fixed
