### ISSUE TITLE
End of game woes

### ISSUE THREAD

**Issue by jonah-henderson** [cs340tabyu/cs340Winter2018#247]
After finishing a game and ending on the game over screen, I pressed 'back' on both devices.

The first one went back to the create game menu. The second went back to the create game menu, but as soon was both were there, I was taken back into the end of my previous game. I played one more turn for each player and was taken back to the end game screen, which then looked like the attachment

no idea where -263 route points came from
![points](https://user-images.githubusercontent.com/8919038/38062895-a4776432-32b3-11e8-857a-3f5c94131f14.png)

**Comment by jerrod-storm** [comment]
Good catch! Turns out we weren't removing the game from the server before sending the players back to the lobby
