### ISSUE TITLE
Starting Game with incorrect destination cards

### ISSUE THREAD

**Issue by markwelker** [cs340tabyu/cs340Winter2018#251]
Received 0 destination cards at the beginning of the game (Selected 2 of them, received none of them). Another person selected 3 and received 2. (Duluth - Houston failed twice on game start)

**Comment by markwelker** [comment]
Addonexus had drawn three, thomas drew 3, artisan drew 2.
![image](https://user-images.githubusercontent.com/35548890/38065116-b6b82374-32be-11e8-8a70-5c3ffbda91a2.png)

**Comment by ephraimkunz** [comment]
Problem is when we select some dest cards in one player, then select and accept in another player, then accept in first player. We need to check if the destCard view is showing before launching a new one.

**Comment by ephraimkunz** [comment]
Fixed
