### ISSUE TITLE
Shuffling faceup cards only at end of turn.

### ISSUE THREAD

**Issue by markwelker** [cs340tabyu/cs340Winter2018#254]
Faceup cards do not shuffle immediately upon 3 faceup wilds (they shuffle at the end of the turn though)

**Comment by ephraimkunz** [comment]
The server is sending two updateDeck messages: one with the reshuffled deck, and then the next with the 3 wild-card deck. This causes the players to get out of sync until another deck update command.

**Comment by ephraimkunz** [comment]
Fixed
