### ISSUE TITLE
Occasionally Cannot Claim Route

### ISSUE THREAD

**Issue by markwelker** [cs340tabyu/cs340Winter2018#258]
Occasionally, even though you have enough cards, a route (or multiple routes) will be missing from the selection screen. This issue usually fixes itself on the next turn.

Expected:
Player should be able to claim any route for which he/she has enough cards.

Steps to Reproduce:
Happens (what appears to be) randomly. See "cannot_choose_route" screenshots for evidence
Have 1 blue, 1 red, 1 black in hand.
Lots of routes should be available (Sault St Marie -> Duluth, Toronto -> Montreal, etc.)
Only 4 single space grey routes are available
![cannot_choose_route_3 next turn](https://user-images.githubusercontent.com/35548890/38064851-80a6b300-32bd-11e8-8186-0a5c49408e95.png)
![cannot_choose_route_1 top shows enough cards](https://user-images.githubusercontent.com/35548890/38064852-80ba60da-32bd-11e8-821f-eefc5c29a9b7.png)
![cannot_choose_route_2](https://user-images.githubusercontent.com/35548890/38064853-80cd9d58-32bd-11e8-9d12-e76e657bc880.png)

**Comment by ephraimkunz** [comment]
This works as designed. You can't mix and match colors, even on a "wildcard" route.
