### ISSUE TITLE
Drawing Non-wild cards second

### ISSUE THREAD

**Issue by markwelker** [cs340tabyu/cs340Winter2018#259]
Issue:
Occasionally, selecting a non-wild card to draw will produce a "You cannot choose a wild as your second card" error.

Expected:
Player should be able to draw a face up non-wild card on second draw, face up deck should display properly

Steps to Reproduce:
Happens randomly. Fixes itself sometimes on next turn.
See "cannot_choose_wild" screenshots for evidence
![cannot_choose_wild_2](https://user-images.githubusercontent.com/35548890/38064912-c3924ee0-32bd-11e8-8a89-59c0b69e73eb.png)
![cannot_choose_wild](https://user-images.githubusercontent.com/35548890/38064913-c3a485a6-32bd-11e8-8f97-0960dd4d7880.png)

**Comment by ephraimkunz** [comment]
Couldn't reproduce. Perhaps is was a result of our decks getting out of sync between client and server and was fixed when we fixed that
