### ISSUE TITLE
Route not claiming

### ISSUE THREAD

**Issue by wconnorr** [cs340tabyu/cs340Winter2018#97]
Sometimes, I try to claim a route and it locks the cards that I can't use for that route, but won't let me use the active cards to claim the route. I can still draw cards to end my turn, but those cards stay locked.

**Comment by sigma144** [comment]
I've noticed that this also tends to happen when you draw one train card and then you try to claim a route. After doing this and drawing the second train card, the cards remain greyed out on your next turn.
